version: '3.5'
services:
 

 web_service:
  build: web_service/
  ports:
   - "4000:4000"
  volumes:
   - ./web_service:/app
  environment:
   - ENV=development
   - PORT=4000
   - DB=mongodb://mongodb:27017/testing
   - ZK=localhost:2181

 app_logic_service:
  build: app_logic_service/
  ports:
   - "4010:4010"
  volumes:
   - ./app_logic_service:/app
  environment:
   - ENV=development
   - PORT=4010
   - DB=mongodb://mongodb:27017/testing
   - ZK=localhost:2181

 auth_service:
  build: auth_service/
  ports:
   - "4020:4020"
  volumes:
   - ./auth_service:/app
  environment:
   - ENV=development
   - PORT=4020
   - DB=mongodb://mongodb:27017/testing
   - SECRET='TOP SECRET'
   - ZK=localhost:2181

 storage_service:
  build: storage_service/
  ports:
   - "4030:4030"
  volumes:
   - ./auth_service:/app
  environment:
   - ENV=development
   - PORT=4030
   - DB=mongodb://mongodb:27017/testing
   - ZK=localhost:2181

 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/db:/usr/data/db
  ports:
   - 4009:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet
 
 zk:
    build: zk_service
    image: zookeeper:latest
    restart: always
    hostname: zk
    ports:
      - 4040:2181
networks:
 default:
  name: web_dev
